name: Deploy the web service
on:
  push:
    branches:
      - master
    paths:
      - 'services/web/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instal dependencies
        run: npm install
      - name: Bootstrap all service
        run: npm run bootstrap
      - name: Deploy the web service
        run: npm run deploy --prefix services/web
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN}}


